create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    username text not null,
    message text not null check (char_length(message) between 1 and 500),
    created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

create policy "chat can be read anonymously"
on public.chat_messages for select
using (true);

create policy "chat can be written anonymously"
on public.chat_messages for insert
with check (true);
